config/routes.rb
Rails.application.routes.draw do
  resources :mems do
    collection do
      get 'my'
      get 'inactive'

    end
  end
  get 'home/index'

  devise_for :users
  resources :dogs
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/models/mem.rb
class Mem < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  after_validation(on: :create) do 
  	self.active = false
  end

  scope :active,->{where active:true}
  scope :inactive,->{where active:false}

end

app/models/user.rb
class User < ActiveRecord::Base

has_many :mems
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :year)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mems_controller.rb
class MemsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :my, :new]
  before_action :set_mem, only: [:show, :edit, :update, :destroy]

  # GET /mems
  # GET /mems.json
  def index
    @mems = Mem.active
  end

  def my
    @mems = current_user.mems
    render :index
  end

  def inactive
    @mems = Mem.inactive
    render :index
  end

  # GET /mems/1
  # GET /mems/1.json
  def show
  end

  # GET /mems/new
  def new
    @mem = Mem.new
  end

  # GET /mems/1/edit
  def edit
  end

  # POST /mems
  # POST /mems.json
  def create
    @mem = current_user.mems.new(mem_params)

    respond_to do |format|
      if @mem.save
        format.html { redirect_to @mem, notice: 'Mem was successfully created.' }
        format.json { render :show, status: :created, location: @mem }
      else
        format.html { render :new }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mems/1
  # PATCH/PUT /mems/1.json
  def update
    respond_to do |format|
      if @mem.update(mem_params)
        format.html { redirect_to @mem, notice: 'Mem was successfully updated.' }
        format.json { render :show, status: :ok, location: @mem }
      else
        format.html { render :edit }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mems/1
  # DELETE /mems/1.json
  def destroy
    @mem.destroy
    respond_to do |format|
      format.html { redirect_to mems_url, notice: 'Mem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mem
      @mem = Mem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mem_params
      params.require(:mem).permit(:name, :description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mems_helper.rb
module MemsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.year %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @dog.year %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kwejk" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Kwejk</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Poczekalnia", inactive_mems_path %></li>
            <li><%= link_to "Memy", mems_path  %></li>
            <li><%= link_to "Moje memy", my_mems_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <% if user_signed_in? %>

              <li><%= link_to "Edit account", edit_user_registration_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

              <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign_up", new_user_registration_path %></li>
              <% end %>


            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/mems/_form.html.erb
<%= form_for @mem, :html => { :class => "form-horizontal mem" } do |f| %>

    <% if @mem.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mem.errors.count, "error") %> prohibited this mem from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mem.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@mem[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@mem[:description]) %>
  </div>

  <div>
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>
  <br>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            mems_path, :class => 'btn btn-default' %>

<% end %>

app/views/mems/edit.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mems/index.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1 style="text-align:center">Tabela <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

    <% @mems.each do |mem| %>
      <div class="mems">
        <h2><%= link_to mem.name, mem_path(mem) %></h2>
        <%= link_to image_tag(mem.image.url(:medium)), mem_path(mem) %>
        <p><%= link_to mem.description %></p>
      </div>
    <% end %>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mem_path,
            :class => 'btn btn-primary' %>

app/views/mems/new.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/mems/show.html.erb
<%- model_class = Mem -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @mem.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @mem.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @mem.user_id %></dd>
  <dt><strong> Fotka</strong></dt>
  <dd><%= image_tag @mem.image.url(:medium) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              mems_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mem_path(@mem), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mem_path(@mem),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>